### ISSUE TITLE
Installed libraries should be symbolic links to one

### ISSUE THREAD

**Issue by yurivict** [grame-cncm/inscore#1]
Revision 6eeab57 installs them as separate files:

```
-rwxr-xr-x  1 root  wheel  7469166 Aug 26 18:03 libINScore.so.1
-rwxr-xr-x  1 root  wheel  7469166 Aug 26 18:03 libINScore.so.1.23
-rwxr-xr-x  1 root  wheel  7469166 Aug 26 18:03 libINScore.so.1.23.0
```

**Comment by dfober** [comment]
that's not the case on my side:
I have symbolic links but I've corrected the missing libINScore.so.
All links point to libINScore.so.1.23.0, that's how qmake generates the output.
Copy is made using `cp -d`
