### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by joachimheintz** [grame-cncm/inscore#19]
i am on debian 11. cloned and went to the build dir, and then `make`.  all seemed to go well, but then:

-- Build files have been written to: /home/jh/src/inscore/modules/guidolib/build/guidodir
make[4]: Leaving directory '/home/jh/src/inscore/modules/guidolib/build'
cd guidodir && cmake --build .  --config Release
gmake[4]: Entering directory '/home/jh/src/inscore/modules/guidolib/build/guidodir'
gmake[5]: Entering directory '/home/jh/src/inscore/modules/guidolib/build/guidodir'
gmake[6]: Entering directory '/home/jh/src/inscore/modules/guidolib/build/guidodir'
CMakeFiles/GUIDOEngine.dir/flags.make:6: *** missing separator.  Stop.
gmake[6]: Leaving directory '/home/jh/src/inscore/modules/guidolib/build/guidodir'
gmake[5]: *** [CMakeFiles/Makefile2:94: CMakeFiles/GUIDOEngine.dir/all] Error 2
gmake[5]: Leaving directory '/home/jh/src/inscore/modules/guidolib/build/guidodir'
gmake[4]: *** [Makefile:103: all] Error 2
gmake[4]: Leaving directory '/home/jh/src/inscore/modules/guidolib/build/guidodir'
make[3]: *** [Makefile:37: basic] Error 2
make[3]: Leaving directory '/home/jh/src/inscore/modules/guidolib/build'
make[2]: *** [Makefile:8: all] Error 2
make[2]: Leaving directory '/home/jh/src/inscore/modules'
make[1]: *** [Makefile:155: modules] Error 2
make[1]: Leaving directory '/home/jh/src/inscore/build'
make: *** [Makefile:31: all] Error 2

i had a look in the file CMakeFiles/GUIDOEngine.dir/flags.make.  it says:
CXX_DEFINES = -DGCC -DGUIDOEngine_EXPORTS -DMIDIEXPORT -DMSLIGHT Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cairo' found

on my system, i find cairo in 
/usr/lib/python3/dist-packages/cairo

any help?
thanks -
  joachim

**Comment by dfober** [comment]
Do you have a file named 'cairo.pc' in your distribution?
Can you run pkg-config manually? i.e. pkg-config --cflags --libs cairo

**Comment by joachimheintz** [comment]
that's the result:

pkg-config --cflags --libs cairo
Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cairo' found

**Comment by dfober** [comment]
It looks like your cairo distribution is part of the python package and it could be the reason why it's not visible.
You should try to install it separately (i.e. apt install cairo-dev)

**Comment by joachimheintz** [comment]
i installed this (i think it is libcairo2-dev on debian) and get now:
pkg-config --cflags --libs cairo
-I/usr/include/cairo -I/usr/include/glib-2.0 
-I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 
-I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -lcairo

but make fails always at the same step:
gmake[6]: Entering directory 
'/home/jh/src/inscore/modules/guidolib/build/guidodir'
CMakeFiles/GUIDOEngine.dir/flags.make:6: *** missing separator.  Stop.

i tried `make claen` in between, but no difference.

**Comment by dfober** [comment]
seems to come from the guidolib. Strange because it compiles correctly on all the supported platforms (see the [github actions](https://github.com/grame-cncm/guidolib/actions). Could you go to the 'modules/guidolib/build' folder, the remove the guidodir folder and do a `make lib`

**Comment by joachimheintz** [comment]
i did, and the lib was built.
i returned to the main build dir, and did make.
the previous error did not appear again, but another one:

CMake Error at modules/QTVIEWConfig.cmake:28 (find_package):
   By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
   asked CMake to find a package configuration file provided by "Qt5", but
   CMake did not find one.

   Could not find a package configuration file provided by "Qt5" with any of
   the following names:

     Qt5Config.cmake
     qt5-config.cmake

   Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set 
"Qt5_DIR"
   to a directory containing one of the above files.  If "Qt5" provides a
   separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
   CMakeLists.txt:180 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/jh/src/inscore/build/inscoredir/CMakeFiles/CMakeOutput.log".
make[1]: *** [Makefile:82: inscoredir/Makefile] Error 1
make[1]: Leaving directory '/home/jh/src/inscore/build'
make: *** [Makefile:32: all] Error 2

**Comment by dfober** [comment]
what version of Qt are you using?
you can get it with the `cmake --version` command

**Comment by joachimheintz** [comment]
i solved this issue by installing a lot of libs: not only qtbase5-dev-tools, but also qtdeclarative5-dev (this was most important), and some others. in total:
 sudo apt install qtbase5-dev-tools
 sudo apt install qtdeclarative5-dev
 sudo apt install libqt5svg5-dev
 sudo apt install qtmultimedia5-dev
 sudo apt install libqt5websockets5-dev
 sudo apt install libqt5sensors5-dev

i suggest to list these libs in the readme for people who want to build on debian.

actually i would have preferred to point to the version which i downloaded from qt (including QtCreator).  but i did not figure out a possibility to configure the makefile or the CMakeLists to do so.  can this be added as a standard option, rather than assuming the Qt from the repositories?
