### ISSUE TITLE
Piano score

### ISSUE THREAD

**Issue by patricio1979** [grame-cncm/inscore#23]
I'm working with Pure Data and Inscore.

I'm not able to write a piano score. Any help?

`{[\pageFormat<"letter",tm= 2cm>\title<"piano">\composer<"El",dy=1> \systemFormat< dx=1cm>\barFormat<"system"> \clef<"g">\meter<"3/4">\tempo<"Adagio",dy=1>\beam (b1/8 a g)],[ \clef<"f">\meter<"3/4">\bm(d/8 c b&0)]}`

I've tried two ways. 
* First building a message but PD does not support the { } characters in a message, so it goes as
`/ITL/score/score set gmn [\\pageFormat<"letter"\,tm= 2cm>\\title<"paino">\\composer<"elPepe"\,dy=1>\\systemFormat<dx=1cm>\\barFormat<"system">\\clef<"g">\\meter<"3/4">\\tempo<"Adagio"\,dy=1>\\beam(b1/8 a g)]\,[\\clef<"f">\\meter<"3/4"m(d/8 c b&0)]
`. 
The inscore log shows 
`error: incorrect parameters: /ITL/score/score set gmn [\pageFormat<"letter",tm= 2cm>\title<"paino">\composer<"elPepe",dy=1>\systemFormat<dx=1cm>\barFormat<"system">\clef<"g">\meter<"3/4">\tempo<"Adagio",dy=1>\beam(b1/8 a g)],[\clef<"f">\meter<"3/4"m(d/8 c b&0)]
`
* Second, having a text editor that has the string, but when saving the file, it deletes the \ characters.

**Comment by dfober** [comment]
Dear Patricio,

The gmn code is correct thus it's likely a problem with PD.
To debug, I suggest to use a gmn stream object (type is gmnstream) see at
https://inscoredoc.grame.fr/refs/8-specificMsg/#symbolic-score
Then, you can send the score part by part and see what part is not
correctly formatted.
Dominique

**Comment by patricio1979** [comment]
Dominique, 
Thank you for your answer.
The two sequences were fine, I also tried the `expr gmn` sum for getting the piano score, but it also didn't work. Is a Pure Data thing, probably associated with the OSC message building. I'm not expert, so the solution I came up with is using Sublime Text for writing the score and using `gmnf` in Pure Data with a `metro` object for actualizing the score. 
But the fight isn't over, now I'm struggling with converting the score into MIDI... 

Thank you again, best wishes
Patricio

**Comment by dfober** [comment]
There is a tool named 'guido2midi' that is part of the guido distribution
<https://github.com/grame-cncm/guidolib/releases>.
usage: guido2midi [option] <gmn file>
       converts the <gmn file> to midi file
       options: -o <midi file> the output file name, defaults to <gmn
file>.mid
Dominique
