### ISSUE TITLE
MobMuPlat implementation

### ISSUE THREAD

**Issue by patricio1979** [grame-cncm/inscore#24]
Hello, is there a way to open inScore in android and receive OSC messages from other apps like, in my case, MobMuPlat? I can't seem to pass data.

Do I need to open a `inscore` file in the app?

**Comment by dfober** [comment]
Hi,  
There are several ways to send messages to remote devices (including Android) :  
- using the [extended osc address](https://inscoredoc.grame.fr/lang/1-scripting/#extended-osc-addresses) : e.g.  `the.target.ip.address:portnum/your message` (in osc format). Note that it isn't restricted to inscore messages, you can send arbitrary osc messages to any osc application
- using [message forwarding](https://inscoredoc.grame.fr/refs/11-forwarding/) : e.g. `/ITL forward "thedevice.hostname or ip address";`  then any message send to inscore will be forwarded to the remote device, including internal messages (like those generated when an object tempo is not 0).  
Note that you can apply [filters](https://inscoredoc.grame.fr/refs/11-forwarding/#filters) to select the messages you want to forward. You can also send the forward message to a scene, then only the scene messages are forwarded.  

Regarding Android, you can check the device IP address with the 'About' menu of the inscore application.
Hope that it helps.
