### ISSUE TITLE
vieo on linux

### ISSUE THREAD

**Issue by thibaudk** [grame-cncm/inscore#9]
On linux, installing qtgstreamer-plugins-qt5
is necessary playing a video in the inscoreviewer.
Maybe the wiki should mention it.

The issue and the solution was found here:

https://forum.qt.io/topic/28620/solved-qtmultimedia-defaultserviceprovider-requestservice-no-service-found-for-org-qt-project-qt-mediaplayer/35

tested on dev branch with Ubuntu 19.04

**Comment by dfober** [comment]
Thanks! It's now mentioned in the [building process](https://github.com/grame-cncm/inscore/wiki/Building).

**Comment by thibaudk** [comment]
Perfect !
Cheers
